theme: jekyll-theme-minimal
title: DASHMM
navpages:
    - title: DASHMM
      url: /
    - title: Details
      url: /details.html
    - title: Resources
      url: /resources.html
    - title: Tutorial
      url: /tutorial.html
    - title: DASHMM Team
      url: /team.html
